### PR TITLE
Nice and clean triangle mixin

### PR DESCRIPTION
**Pull request by r007**
Because triangle can be created with 2 lines of code ONLY. 

Top-left example:

``` css
border-top: $height solid transparent;
border-left: $width solid $color;
```

### CODE REVIEW

**Comment by r007** [comment]
Need a review for multiline ellipsis - not sure if correct or not.

**Comment by MoOx** [comment]
Thanks for you work. Can you make a separates PR for multilines ellipsis ? And add a "test" html page like I did for others stuffs please ?

**Comment by MoOx** [comment]
What about the things I ask ? ping @r007 :)

**Comment by r007** [comment]
Sorry for the late answer, busiest ever. Yes, I think I can do it. I just didn't understand the meaning of "separates PR". What do you mean by that? PS. I can't believe it's been 3 months ago!

**Comment by r007** [comment]
Although, I don't know how will be helpful ellipsis. Because in real projects it more appropriate to use dotdotdot plugin, instead of css-only crooked nail.

**Comment by MoOx** [comment]
I think I'll just take a look to the #72 & maybe cherry pick you commit about that.
Not sure about the multilines ellipsis.

**Pull request closed without merging**
