### PR TITLE
Adding more CSS background patterns. 

### PR DESCRIPTION
**Pull request by codingdesigner**
I had started a private project of writing the Lea Verou patterns as Compass mixins and found out about your project. I had some time this weekend to work out a few more of them and thought I'd run them by you. They're pretty straightforward, but I am trying to write them so they're flexible and usable.

### CODE REVIEW

**Comment by MoOx** [comment]
Well done. Please can you just indent your code like us (4 spaces) before I'll merge this ?

**Comment by codingdesigner** [comment]
no problem. Here you go.

**Comment by MoOx** [comment]
Thanks for your work !

**Comment by codingdesigner** [comment]
my pleasure. I have some other things that might fit this project. I'll probably submit them as well soon.

**Comment by MoOx** [comment]
Please pull :)

**Pull request merged**
