### PR TITLE
Prettier lifted corners effect

### PR DESCRIPTION
**Pull request by michaek**
This isn't substantially different from the current lifted corners effect, but it's closer to Matt Hamm's updated  implementation.

When I use this on my markup, it looks great, but I wasn't able to apply it to the tests (or regenerate the Github pages). That's something I'd like to get sorted out, but I wanted to make this pull request in any case.

### CODE REVIEW

**Comment by MoOx** [comment]
With your modification, I get that on the test http://cl.ly/3q163R19472B3a0N3y2A
To be able to use the tests under "/tests", you just need to use `compass watch`or `compass compile` at the root of the compass recipes folder, then you can view `{your-path}/tests/recipes/shadow/drop/index.html`

**Comment by michaek** [comment]
Yes, that's what I got when I ran compass compile. It's not what I'm getting in practice, so I might take another look at the test.

However I also got a lot of other changes in the CSS output across the tests, which doesn't seem appropriate when I was making a change that should only affect one test. Hard to trust the tests when that happens...

**Comment by MoOx** [comment]
The tests are supposed to reproduce one or more example with the minimal code around. If you have "in practice" a different behavior, I encourage you to isolate your code (eg on dabblet.com, cssdesk.com, jsfiddle.com...) to check if there is really an issue. I've take a look at your code, & it seems you change a z-index you should not (because the :after, is after, when an element have the same z-index than it :after element, the :after apply a +1, and so is above).

If you find something weird, do no hesitate to open a issue.
I encouter problem with coworkers working on a different OS (like some code output compiling to .rule, .rule2 & .rule,{\n}.rules2...)
I guess the (bad) thing is I use sass --pre right now.
I will do like compass does asap, using a stable branch for the current stable version of sass/compass & the master for the --pre versions.

**Comment by michaek** [comment]
I agree with you, Maxime. I'm going to address the problems with the test and double-check the z-index. That won't explain the weird stuff that's happening with the geometry of the shadows in the tests. I'm going to close this pull request and make a new one with good test output.

**Comment by MoOx** [comment]
You can just reopen & continue to push on the same branch, it will automatically be added to this pr by github

**Comment by MoOx** [comment]
It's nice to archive evolution off the code on a PR.
Anyway thanks for your contribution !

**Comment by michaek** [comment]
Maxime, can you provide some more detailed information about the gem versions you're using for development? The Gemfile doesn't specify, and I'd like to be able to replicate your output. Thanks!

**Comment by MoOx** [comment]
I still new to ruby & gem, I just learn things about Gemfile this weekend, so I will add a Gemfile asap.

**Comment by michaek** [comment]
There's already a Gemfile, actually, it just doesn't specify the versions of the gems you're using. If you run "gem list" you'll get the list of installed gems and their versions. I'll try a couple different versions and see if I can get "compass compile" to output CSS without substantial changes.

**Comment by michaek** [comment]
Oh - it's totally in the gemspec. I really should have looked there before asking.

**Comment by MoOx** [comment]
Can you please just remove the .rvmrc file before I merge please ?

And maybe edit one thing or two to have the same result as the original (updated) Matt does ?
Actual : http://cl.ly/3R1P3j1l0S3o0Z3H3J2T
Proposal : http://cl.ly/0w3U403H3Q0a2n1m1W1C
Matt Hamm's updated : http://cl.ly/0Y222F1K2m36281x3q2M

Thanks !

**Comment by michaek** [comment]
I haven't dealt with a pull request from the receiving end, but I think you can reject certain commits. Since the rvmrc is added in a commit on its own, that shouldn't cause any problems.

Are you asking that the defaults be set so you get the same effect as Matt's approach if you use the mixin without parameters? I can do that, but I might not be able to get around to it today.

**Comment by MoOx** [comment]
I'll take a look tonight maybe.
Thanks anyway for your contribution.

**Comment by michaek** [comment]
Hi, Maxime. Can you clarify that's what you meant? I'll adjust the defaults, but I'd like to be sure that's what you were talking about.

**Comment by MoOx** [comment]
Yes that's it. Change the default to look like the original one.

**Comment by michaek** [comment]
Hm - I think the original corners don't look right. That's part of the reason for changing them! I think it would be better for the implementation to match Matt Hamm's example: http://cl.ly/0Y222F1K2m36281x3q2M

**Comment by MoOx** [comment]
Oh sorry that what I mean when I say "original" one. That's why I show the 3 screenshots :)
Go for having default value like the Matt Hamm's example.

(Maybe sometimes I don't understand the thing you said right or I made mistakes when I express myself. English is not my natif language)

**Comment by MoOx** [comment]
Merged with 01debda5484802a36077863c9ea01d48ece54e97

**Pull request closed without merging**
